############# English navigation ##############

# main menu
[[main]]
  name = "Accueil"
  pageRef = "/"
  weight = 1

[[main]]
  name = "À propos"
  pageRef = "/about"
  weight = 2

[[main]]
  name = "Contactez-nous"
  url = "https://calendly.com/geekie-app/contact"
  weight = 3

  # [[main]]
  #   name = "Pages"
  #   weight = 4

  # [[main]]
  #   name = "Blog"
  #   pageRef = "/blog"
  #   parent = "Pages"

  # [[main]]
  #   name = "Contact"
  #   pageRef = "/contact"
  #   parent = "Pages"

  # [[main]]
  #   name = "Authors"
  #   pageRef = "/authors"
  #   parent = "Pages"

  # [[main]]
  #   name = "Categories"
  #   pageRef = "/categories"
  #   parent = "Pages"

  # [[main]]
  #   name = "404 Page"
  #   pageRef = "/404"
  #   parent = "Pages"


# footer menu
# [[footer]]
#   name = "About"
#   pageRef = "/about"
#   weight = 1

# [[footer]]
#   name = "Elements"
#   pageRef = "/elements"
#   weight = 2

# [[footer]]
#   name = "Privacy Policy"
#   pageRef = "/privacy-policy"
#   weight = 3
