############# English navigation ##############

# main menu
[[main]]
  name = "Accueil"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Nos formateurs"
  pageRef = "/our-trainers"
  weight = 2

[[main]]
  name = "Contactez-nous"
  url = "https://calendly.com/geekie-app/contact"
  weight = 3

  # [[main]]
  #   name = "Pages"
  #   weight = 4

  # [[main]]
  #   name = "Blog"
  #   pageRef = "/blog"
  #   parent = "Pages"

  # [[main]]
  #   name = "Contact"
  #   pageRef = "/contact"
  #   parent = "Pages"

  # [[main]]
  #   name = "Authors"
  #   pageRef = "/authors"
  #   parent = "Pages"

  # [[main]]
  #   name = "Categories"
  #   pageRef = "/categories"
  #   parent = "Pages"

  # [[main]]
  #   name = "404 Page"
  #   pageRef = "/404"
  #   parent = "Pages"


# footer menu
[[footer]]
  name = "CGV"
  url = "/documents/terms-of-sales.pdf"
  weight = 1

[[footer]]
  name = "CGU"
  url = "/documents/terms-of-service.pdf"
  weight = 2

[[footer]]
  name = "Règlement interieur des formations"
  url = "/documents/internal-regulations.pdf"
  weight = 3

[[footer]]
  name = "RGPD"
  url = "/documents/general-data-protection-regulation.pdf"
  weight = 4

[[footer]]
  name = "Cookie"
  url = "/documents/cookie.pdf"
  weight = 5

[[footer]]
  name = "Politique de confidentialité"
  url = "/documents/privacy-policy.pdf"
  weight = 6

[[footer]]
  name = "Mentions légales"
  url = "/documents/legal-notice.pdf"
  weight = 7
